Repository RachitDiaz/Vorlagenersteller_S.A, pull requests merged in 2025-07, with the labels that each got.

#103 Implementada la eliminación de empelado
  BackEnd/backend-planilla/PlanillaTest/EmpleadoQueryTests/EliminarEmpleadoTest.cs
  BackEnd/backend-planilla/PlanillaTest/EmpleadoQueryTests/EmpleadoQueryTest.cs
  BackEnd/backend-planilla/PlanillaTest/PlanillaTest.csproj
  BackEnd/backend-planilla/backend-planilla/API/EmpleadoController.cs
  BackEnd/backend-planilla/backend-planilla/Application/EmpleadoQuery.cs
  BackEnd/backend-planilla/backend-planilla/Application/IEmpleadoQuery.cs
  BackEnd/backend-planilla/backend-planilla/Infraestructure/EmpleadoRepository.cs
  BackEnd/backend-planilla/backend-planilla/Infraestructure/IEmpleadoRepository.cs
  BackEnd/backend-planilla/backend-planilla/Infraestructure/LoginHandler.cs
  DB/scripts/VorlagenerstellerQuery19.sql
  FrontEnd/frontend-planilla/src/components/dueno/ListaEmpleados.vue
  FrontEnd/frontend-planilla/src/components/modals/ModalEliminarEmpleado.vue
Labels: Aprobado por alguno, Sprint 3

#105 Dashboard Empleado y Ver Empleado
  BackEnd/backend-planilla/PlanillaTest/BeneficioQueryTest.cs
  BackEnd/backend-planilla/PlanillaTest/GetDeduccionBeneficiosQueryTests.cs
  BackEnd/backend-planilla/backend-planilla/API/BeneficiosController.cs
  BackEnd/backend-planilla/backend-planilla/API/DeduccionesBeneficiosController.cs
  BackEnd/backend-planilla/backend-planilla/API/EmpleadoController.cs
  BackEnd/backend-planilla/backend-planilla/API/ReportesController.cs
  BackEnd/backend-planilla/backend-planilla/Application/DeduccionCalculada.cs
  BackEnd/backend-planilla/backend-planilla/Application/EmpleadoQuery.cs
  BackEnd/backend-planilla/backend-planilla/Application/GetDeduccionBeneficiosQuery.cs
  BackEnd/backend-planilla/backend-planilla/Application/IEmpleadoQuery.cs
  BackEnd/backend-planilla/backend-planilla/Application/IGetDeduccionBeneficiosQuery.cs
  BackEnd/backend-planilla/backend-planilla/Program.cs
  FrontEnd/frontend-planilla/package.json
  FrontEnd/frontend-planilla/src/components/MainLogin.vue
  FrontEnd/frontend-planilla/src/components/VerEmpleado.vue
  FrontEnd/frontend-planilla/src/components/dueno/ListaBeneficios.vue
  FrontEnd/frontend-planilla/src/components/dueno/ListaEmpleados.vue
  FrontEnd/frontend-planilla/src/components/empleado/BeneficiosSeleccionados.vue
  FrontEnd/frontend-planilla/src/components/empleado/DashboardEmpleado.vue
  FrontEnd/frontend-planilla/src/components/empleado/ReportePagoPlanilla.vue
  FrontEnd/frontend-planilla/src/components/empleado/VerEmpleado.vue
  FrontEnd/frontend-planilla/src/components/header/AppHeader.vue
  FrontEnd/frontend-planilla/src/components/modals/ModalEditarEmpleado.vue
  FrontEnd/frontend-planilla/src/components/modals/ModalVerEmpleado.vue
  FrontEnd/frontend-planilla/src/main.js
Labels: Aprobado por alguno, Sprint 3

#108 ListaEmpresas y VerEmpresa
  BackEnd/backend-planilla/backend-planilla/API/EmpresaController.cs
  BackEnd/backend-planilla/backend-planilla/Infraestructure/EmpresaHandler.cs
  DB/scripts/VorlagenerstellerQuery19.sql
  FrontEnd/frontend-planilla/package-lock.json
  FrontEnd/frontend-planilla/src/components/dueno/ListaBeneficios.vue
  FrontEnd/frontend-planilla/src/components/dueno/ListaEmpleados.vue
  FrontEnd/frontend-planilla/src/components/dueno/ListaEmpresas.vue
  FrontEnd/frontend-planilla/src/components/dueno/VerEmpresa.vue
  FrontEnd/frontend-planilla/src/components/header/AppHeader.vue
  FrontEnd/frontend-planilla/src/components/modals/ModalVerEmpresa.vue
  FrontEnd/frontend-planilla/src/main.js
Labels: Sprint 3

#114 Se completa GenerarPlanilla
  BackEnd/backend-planilla/PlanillaTest/GenerarPlanillaTests/GenerarCalculosQueryTests.cs
  BackEnd/backend-planilla/PlanillaTest/GenerarPlanillaTests/GenerarPlanillaTests.cs
  BackEnd/backend-planilla/backend-planilla/API/GenerarPlanillaController.cs
  BackEnd/backend-planilla/backend-planilla/Application/GenerarCalculosQuery.cs
  BackEnd/backend-planilla/backend-planilla/Application/GenerarPlanilla.cs
  BackEnd/backend-planilla/backend-planilla/Application/IGenerarCalculosQuery.cs
  BackEnd/backend-planilla/backend-planilla/Application/IGenerarPlanilla.cs
  BackEnd/backend-planilla/backend-planilla/Domain/GenerarPlanillaRequestModel.cs
  BackEnd/backend-planilla/backend-planilla/Domain/ResultadoEmpleadoModel.cs
  BackEnd/backend-planilla/backend-planilla/Infraestructure/GenerarCalculosRepository.cs
  BackEnd/backend-planilla/backend-planilla/Infraestructure/IGenerarCalculosRepository.cs
  BackEnd/backend-planilla/backend-planilla/Infraestructure/IPlanillaRepository.cs
  BackEnd/backend-planilla/backend-planilla/Infraestructure/PlanillaRepository.cs
  BackEnd/backend-planilla/backend-planilla/Program.cs
  DB/scripts/VorlagenerstellerQuery23.sql
  FrontEnd/frontend-planilla/src/components/dueno/Planilla.vue
  FrontEnd/readme.md
Labels: Sprint 3, Hacer UnitTest

#116 Agregado UI Test de agregar y eliminar un empleado
  BackEnd/backend-planilla/PlanillaTest/PlanillaTest.csproj
  BackEnd/backend-planilla/PlanillaTest/UITests/UITest004.cs
  BackEnd/backend-planilla/backend-planilla/Program.cs
  BackEnd/backend-planilla/backend-planilla/appsettings.json
  BackEnd/backend-planilla/backend-planilla/backend-planilla.csproj
Labels: Aprobado por alguno, Sprint 3

#117 UITest de Login
  BackEnd/backend-planilla/PlanillaTest/GenerarPlanillaTests/GenerarPlanillaTests.cs
  BackEnd/backend-planilla/PlanillaTest/PlanillaTest.csproj
  BackEnd/backend-planilla/PlanillaTest/UITests/LoginTestUI.cs
  BackEnd/backend-planilla/PlanillaTest/UnitTests/GenerarPlanillaTests/GenerarCalculosQueryTests.cs
  BackEnd/backend-planilla/PlanillaTest/UnitTests/GenerarPlanillaTests/GenerarPlanillaTests.cs
  BackEnd/backend-planilla/backend-planilla/Application/GenerarPlanilla.cs
Labels: Aprobado por alguno, Sprint 3
