Repository RachitDiaz/Vorlagenersteller_S.A, pull requests merged in 2025-05, with the labels that each got.

#4 Se implementa un form para agregar un beneficio nuevo
  FrontEnd/frontend-planilla/package-lock.json
  FrontEnd/frontend-planilla/package.json
  FrontEnd/frontend-planilla/public/index.html
  FrontEnd/frontend-planilla/src/App.vue
  FrontEnd/frontend-planilla/src/components/AgregarBeneficios.vue
  FrontEnd/frontend-planilla/src/components/HelloWorld.vue
  FrontEnd/frontend-planilla/src/components/modals/ModalAgregarBeneficios.vue
  FrontEnd/frontend-planilla/src/main.js
Labels: Aprobado por alguno

#9 Actualización de todos los readme.md
  BackEnd/readme.md
  DB/readme.md
  DB/scripts/eliminar_cuando_alguien_suba_el_primer_script
  FrontEnd/readme.md
  readme.md
Labels: documentation, Aprobado por alguno

#11 añadí lso frotnedns finales para revisión
  FrontEnd/frontend-planilla/src/components/AgregarBeneficios.vue
  FrontEnd/frontend-planilla/src/components/dueno/AdministrarEmpleados.vue
  FrontEnd/frontend-planilla/src/components/dueno/AgregarBeneficio.vue
  FrontEnd/frontend-planilla/src/components/empleado/BeneficiosSeleccionados.vue
  FrontEnd/frontend-planilla/src/components/modals/ModalAgregarEmpleado.vue
  FrontEnd/frontend-planilla/src/main.js
Labels: Aprobado por alguno

#12 Aldo
  DB/design/Diseño_Relacional.png
  DB/design/Diseño_Relacional.svg
  FrontEnd/frontend-planilla/src/components/ListaEmpresas.vue
  FrontEnd/frontend-planilla/src/components/VerEmpresa.vue
  FrontEnd/frontend-planilla/src/components/modals/ModalRegistrarEmpresa.vue
  FrontEnd/frontend-planilla/src/main.js
Labels: Aprobado por alguno

#13 Se une front-end y back-end de login
  BackEnd/backend-planilla/backend-planilla/Controllers/LoginController.cs
  BackEnd/backend-planilla/backend-planilla/Controllers/WeatherForecastController.cs
  BackEnd/backend-planilla/backend-planilla/Program.cs
  BackEnd/backend-planilla/backend-planilla/WeatherForecast.cs
  FrontEnd/frontend-planilla/src/components/MainLogin.vue
  FrontEnd/readme.md
Labels: Aprobado por alguno

#14 Daniel
  BackEnd/backend-planilla/backend-planilla/Controllers/ListaBeneficiosController.cs
  BackEnd/backend-planilla/backend-planilla/Handlers/BeneficiosHandler.cs
  BackEnd/backend-planilla/backend-planilla/Models/BeneficioModel.cs
  BackEnd/backend-planilla/backend-planilla/Models/ParametroBeneficioModel.cs
  BackEnd/backend-planilla/backend-planilla/Program.cs
  BackEnd/backend-planilla/backend-planilla/appsettings.json
  BackEnd/backend-planilla/backend-planilla/backend-planilla.csproj
  FrontEnd/frontend-planilla/src/components/modals/ModalAgregarBeneficios.vue
Labels: Aprobado por alguno

#15 Se actualiza back-end de login
  BackEnd/backend-planilla/backend-planilla/Controllers/LoginController.cs
  BackEnd/backend-planilla/backend-planilla/Models/LoginRequestModel.cs
  BackEnd/backend-planilla/backend-planilla/Services/AuthService.cs
  FrontEnd/frontend-planilla/README.md
Labels: Aprobado por alguno

#16 Implementado modal en ListaBeneficios
  BackEnd/backend-planilla/backend-planilla/Controllers/ListaBeneficiosController.cs
  BackEnd/backend-planilla/backend-planilla/Handlers/BeneficiosHandler.cs
  FrontEnd/frontend-planilla/src/components/dueno/ListaBeneficios.vue
  FrontEnd/frontend-planilla/src/components/modals/ModalAgregarBeneficios.vue
  FrontEnd/frontend-planilla/src/components/modals/ModalAgregarEmpleado.vue
  FrontEnd/frontend-planilla/src/main.js
Labels: Aprobado por alguno

#18 Se implementa un sistema de tokens JWT y conexión login-DB.
  BackEnd/backend-planilla/backend-planilla/Controllers/ListaBeneficiosController.cs
  BackEnd/backend-planilla/backend-planilla/Controllers/LoginController.cs
  BackEnd/backend-planilla/backend-planilla/Handlers/LoginHandler.cs
  BackEnd/backend-planilla/backend-planilla/Program.cs
  BackEnd/backend-planilla/backend-planilla/appsettings.json
  BackEnd/backend-planilla/backend-planilla/backend-planilla.csproj
  DB/scripts/VorlagenerstellerQuery1.sql
  DB/scripts/eliminar_cuando_alguien_suba_el_primer_script
  FrontEnd/frontend-planilla/src/components/ListaEmpresas.vue
  FrontEnd/frontend-planilla/src/components/MainLogin.vue
  FrontEnd/frontend-planilla/src/components/RegistrarDueno.vue
  FrontEnd/frontend-planilla/src/components/VerEmpresa.vue
  FrontEnd/frontend-planilla/src/components/dueno/AdministrarEmpleados.vue
  FrontEnd/frontend-planilla/src/components/dueno/ListaBeneficios.vue
  FrontEnd/frontend-planilla/src/components/empleado/BeneficiosSeleccionados.vue
  FrontEnd/frontend-planilla/src/components/modals/ModalAgregarBeneficios.vue
  FrontEnd/frontend-planilla/src/main.js
  FrontEnd/readme.md
Labels: Aprobado por alguno

#19 Se añaden scripts y modifican archivos con ñ
  DB/scripts/VorlagenerstellerQuery1.sql
  DB/scripts/VorlagenerstellerQuery2.sql
Labels: Aprobado por alguno

#20 Relación de los beneficios con cada empresa
  BackEnd/backend-planilla/backend-planilla/Controllers/ListaBeneficiosController.cs
  BackEnd/backend-planilla/backend-planilla/Handlers/BeneficiosHandler.cs
  BackEnd/backend-planilla/backend-planilla/Handlers/LoginHandler.cs
  FrontEnd/frontend-planilla/src/components/MainLogin.vue
  FrontEnd/frontend-planilla/src/components/dueno/ListaBeneficios.vue
  FrontEnd/frontend-planilla/src/components/modals/ModalAgregarBeneficios.vue
Labels: Aprobado por alguno

#22 Se termina la lista de empleados
  BackEnd/backend-planilla/backend-planilla/Controllers/EmpleadoController.cs
  BackEnd/backend-planilla/backend-planilla/Controllers/ListaBeneficiosController.cs
  BackEnd/backend-planilla/backend-planilla/Handlers/EmpleadoHandler.cs
  BackEnd/backend-planilla/backend-planilla/Models/EmpleadoModel.cs
  BackEnd/backend-planilla/backend-planilla/Models/PersonaModel.cs
  BackEnd/backend-planilla/backend-planilla/Models/SolicitudAgregarEmpleadoModel.cs
  BackEnd/backend-planilla/backend-planilla/Models/UsuarioModel.cs
  FrontEnd/frontend-planilla/src/components/dueno/ListaBeneficios.vue
  FrontEnd/frontend-planilla/src/components/dueno/ListaEmpleados.vue
  FrontEnd/frontend-planilla/src/components/modals/ModalAgregarEmpleado.vue
  FrontEnd/frontend-planilla/src/main.js
Labels: Aprobado por alguno

#23 implementacion de interaccion de VerEmpresa y VerEmpleado con los endpoints correspondientes
  BackEnd/backend-planilla/backend-planilla/Handlers/EmpresaHandler.cs
  BackEnd/backend-planilla/backend-planilla/Models/EmpresaModel.cs
  DB/scripts/VorlagenerstellerQuery1.sql
  DB/scripts/VorlagenerstellerQuery3.sql
  FrontEnd/frontend-planilla/src/components/VerEmpleado.vue
  FrontEnd/frontend-planilla/src/components/VerEmpresa.vue
  FrontEnd/frontend-planilla/src/components/modals/ModalRegistrarEmpresa.vue
Labels: Aprobado por alguno

#24 Se añade hash en login
  BackEnd/backend-planilla/backend-planilla/Handlers/LoginHandler.cs
Labels: Aprobado por alguno

#25 SVG del diagrama de clases
  UMLVorlagenersteller.S.A.svg
Labels: Aprobado por alguno

#26 Se actualiza readme de backend
  BackEnd/readme.md
  UML/UMLVorlagenersteller.S.A.svg
Labels: documentation, Aprobado por alguno

#27 Añadi el header que envie a landing page, el boton de inciair y cerra…
  .vscode/settings.json
  BackEnd/backend-planilla/backend-planilla/Controllers/DuenoController.cs
  BackEnd/backend-planilla/backend-planilla/Handlers/DuenoHandler.cs
  BackEnd/backend-planilla/backend-planilla/Handlers/LoginHandler.cs
  BackEnd/backend-planilla/backend-planilla/Models/DuenoModel.cs
  FrontEnd/frontend-planilla/src/components/MainLogin.vue
  FrontEnd/frontend-planilla/src/components/RegistrarDueno.vue
  FrontEnd/frontend-planilla/src/components/header/AppHeader.vue
  FrontEnd/frontend-planilla/src/components/modals/ModalAgregarEmpleado.vue
Labels: Aprobado por alguno

#29 Correcciones en elegir beneficios
  BackEnd/backend-planilla/backend-planilla/Controllers/EmpleadoController.cs
  BackEnd/backend-planilla/backend-planilla/Controllers/EmpresaController.cs
  BackEnd/backend-planilla/backend-planilla/Handlers/EmpleadoHandler.cs
  BackEnd/backend-planilla/backend-planilla/Handlers/EmpresaHandler.cs
  BackEnd/backend-planilla/backend-planilla/Models/EmpresaModel.cs
  BackEnd/backend-planilla/backend-planilla/appsettings.json
  DB/scripts/VorlagenerstellerQuery1.sql
  DB/scripts/VorlagenerstellerQuery2.sql
  DB/scripts/VorlagenerstellerQuery3.sql
  DB/scripts/VorlagenerstellerQuery4.sql
  FrontEnd/frontend-planilla/src/components/VerEmpleado.vue
  FrontEnd/frontend-planilla/src/components/VerEmpresa.vue
  FrontEnd/frontend-planilla/src/components/dueno/ListaBeneficios.vue
  FrontEnd/frontend-planilla/src/components/empleado/BeneficiosSeleccionados.vue
Labels: Aprobado por alguno

#30 Se coloca el sprint 1 en "producción"
  BackEnd/backend-planilla/backend-planilla/Controllers/EmpleadoController.cs
  DB/scripts/VorlagenerstellerQuery4.sql
  FrontEnd/frontend-planilla/src/components/VerEmpleado.vue
  FrontEnd/frontend-planilla/src/components/VerEmpresa.vue
  FrontEnd/frontend-planilla/src/components/empleado/BeneficiosSeleccionados.vue
Labels: Aprobado por todos

#33 Ajustes para comenzar refactorización de carpetas
  BackEnd/backend-planilla/backend-planilla/appsettings.json
  DB/scripts/VorlagenerstellerQuery4.sql
Labels: Aprobado por alguno, Inicio Sprint 2

#57 Validacion de entradas a backend al agregar empresas
  BackEnd/backend-planilla/backend-planilla/API/EmpresaController.cs
  BackEnd/backend-planilla/backend-planilla/Application/EmpresaQuerry.cs
  BackEnd/backend-planilla/backend-planilla/appsettings.json
  DB/design/Diseño_Relacional.png
  DB/design/Diseño_Relacional.svg
  DB/design/Implementacion-Diseño_Relacional.png
  FrontEnd/frontend-planilla/src/components/modals/ModalRegistrarEmpresa.vue
Labels: Aprobado por alguno

#58 Elegir Beneficios
  BackEnd/backend-planilla/backend-planilla/API/DuenoController.cs
  BackEnd/backend-planilla/backend-planilla/API/EmpleadoController.cs
  BackEnd/backend-planilla/backend-planilla/API/EmpresaController.cs
  BackEnd/backend-planilla/backend-planilla/API/ListaBeneficiosController.cs
  BackEnd/backend-planilla/backend-planilla/Application/EmpresaQuery.cs
  BackEnd/backend-planilla/backend-planilla/Application/IEmpresaQuery.cs
  BackEnd/backend-planilla/backend-planilla/Domain/EmpresaModel.cs
  BackEnd/backend-planilla/backend-planilla/Infraestructure/BeneficiosHandler.cs
  BackEnd/backend-planilla/backend-planilla/Infraestructure/EmpresaHandler.cs
  BackEnd/backend-planilla/backend-planilla/Infraestructure/EmpresaRepository.cs
  BackEnd/backend-planilla/backend-planilla/Infraestructure/IEmpresaRepository.cs
  DB/scripts/VorlagenerstellerQuery6.sql
  FrontEnd/frontend-planilla/src/components/MainLogin.vue
  FrontEnd/frontend-planilla/src/components/RegistrarDueno.vue
  FrontEnd/frontend-planilla/src/components/header/AppHeader.vue
  FrontEnd/frontend-planilla/src/components/modals/ModalAgregarEmpleado.vue
  FrontEnd/frontend-planilla/src/components/modals/ModalRegistrarEmpresa.vue
Labels: Sprint 2

#60 Se hace la refactorización de los beneficios
  BackEnd/API-MediSeguro/API-MediSeguro/.config/dotnet-tools.json
  BackEnd/backend-planilla/backend-planilla/API/BeneficiosController.cs
  BackEnd/backend-planilla/backend-planilla/API/ListaBeneficiosController.cs
  BackEnd/backend-planilla/backend-planilla/Application/BeneficiosQuery.cs
  BackEnd/backend-planilla/backend-planilla/Application/IBeneficiosQuery.cs
  BackEnd/backend-planilla/backend-planilla/Domain/BeneficioModel.cs
  BackEnd/backend-planilla/backend-planilla/Domain/ParametroBeneficioModel.cs
  BackEnd/backend-planilla/backend-planilla/Infraestructure/BeneficiosHandler.cs
  BackEnd/backend-planilla/backend-planilla/Infraestructure/BeneficiosRepository.cs
  BackEnd/backend-planilla/backend-planilla/Infraestructure/IBeneficiosRepository.cs
  BackEnd/backend-planilla/backend-planilla/Program.cs
  DB/scripts/VorlagenerstellerQuery7.sql
  DB/scripts/VorlagenerstellerQuery8.sql
  DB/scripts/VorlagenerstellerQuery9.sql
  FrontEnd/frontend-planilla/.eslintrc.js
  FrontEnd/frontend-planilla/.gitignore
  FrontEnd/frontend-planilla/eslint.config.mjs
  FrontEnd/frontend-planilla/package-lock.json
  FrontEnd/frontend-planilla/package.json
  FrontEnd/frontend-planilla/src/components/MainLogin.vue
  FrontEnd/frontend-planilla/src/components/dueno/ListaBeneficios.vue
  FrontEnd/frontend-planilla/src/components/modals/ModalAgregarBeneficios.vue
  FrontEnd/frontend-planilla/vue.config.js
Labels: Aprobado por alguno, Sprint 2

#61 Se añade interfaz de añadir horas
  DB/scripts/VorlagenerstellerQuery6.sql
  FrontEnd/frontend-planilla/src/components/RegistrarHoras.vue
  FrontEnd/frontend-planilla/src/components/header/AppHeader.vue
  FrontEnd/frontend-planilla/src/main.js
Labels: Aprobado por alguno, Sprint 2
