Repository RachitDiaz/Vorlagenersteller_S.A, pull requests merged in 2025-06, with the labels that each got.

#63 Se agregan sin problema los beneficios sean del tipo que sean
  BackEnd/backend-planilla/backend-planilla/API/BeneficiosController.cs
  BackEnd/backend-planilla/backend-planilla/Application/BeneficiosQuery.cs
  BackEnd/backend-planilla/backend-planilla/Domain/BeneficioModel.cs
  BackEnd/backend-planilla/backend-planilla/Domain/ParametroBeneficioModel.cs
  BackEnd/backend-planilla/backend-planilla/Exceptions/ResourceAlreadyExistsException.cs
  BackEnd/backend-planilla/backend-planilla/Infraestructure/BeneficiosRepository.cs
  BackEnd/backend-planilla/backend-planilla/Infraestructure/IBeneficiosRepository.cs
  DB/scripts/VorlagenerstellerQuery11.sql
  FrontEnd/frontend-planilla/src/components/dueno/ListaBeneficios.vue
  FrontEnd/frontend-planilla/src/components/modals/ModalAgregarBeneficios.vue
Labels: Aprobado por alguno

#64 Solucion a ElegirBeneficios: https://rachitdiaz08.atlassian.net/browse/SCRUM-9
  BackEnd/backend-planilla/backend-planilla/API/BeneficioEmpleadoController.cs
  BackEnd/backend-planilla/backend-planilla/API/BeneficiosController.cs
  BackEnd/backend-planilla/backend-planilla/API/EmpleadoController.cs
  BackEnd/backend-planilla/backend-planilla/API/LoginController.cs
  BackEnd/backend-planilla/backend-planilla/Application/BeneficioQuery.cs
  BackEnd/backend-planilla/backend-planilla/Application/BeneficiosQuery.cs
  BackEnd/backend-planilla/backend-planilla/Application/iBeneficioQuery.cs
  BackEnd/backend-planilla/backend-planilla/Domain/BeneficioEmpleadoModel.cs
  BackEnd/backend-planilla/backend-planilla/Domain/BeneficioSimpleModel.cs
  BackEnd/backend-planilla/backend-planilla/Infraestructure/BeneficioRepository.cs
  BackEnd/backend-planilla/backend-planilla/Infraestructure/BeneficiosRepository.cs
  BackEnd/backend-planilla/backend-planilla/Infraestructure/IBeneficioRepository.cs
  DB/scripts/VorlagenerstellerQuery12.sql
  FrontEnd/frontend-planilla/src/components/MainLogin.vue
  FrontEnd/frontend-planilla/src/components/dueno/ListaBeneficios.vue
  FrontEnd/frontend-planilla/src/components/dueno/ListaEmpresas.vue
  FrontEnd/frontend-planilla/src/components/dueno/VerEmpresa.vue
  FrontEnd/frontend-planilla/src/components/empleado/BeneficiosSeleccionados.vue
  FrontEnd/frontend-planilla/src/components/empleado/RegistrarHoras.vue
  FrontEnd/frontend-planilla/src/components/header/AppHeader.vue
  FrontEnd/frontend-planilla/src/main.js
Labels: Aprobado por alguno, Sprint 2

#67 Proyecto para pruebas
  BackEnd/backend-planilla/PlanillaTest/EmpresaQueryTest.cs
  BackEnd/backend-planilla/PlanillaTest/PlanillaTest.csproj
  BackEnd/backend-planilla/backend-planilla.sln
  BackEnd/backend-planilla/backend-planilla/Application/EmpresaQuery.cs
  BackEnd/readme.md
Labels: Aprobado por alguno, Sprint 2

#68 Calcular planilla mensual
  BackEnd/backend-planilla/backend-planilla/API/DeduccionesPlanillaController.cs
  BackEnd/backend-planilla/backend-planilla/Application/CalcularDeduccionesPlanilla.cs
  BackEnd/backend-planilla/backend-planilla/Domain/DeduccionesPlanillaModel.cs
  BackEnd/backend-planilla/backend-planilla/Program.cs
  DB/scripts/VorlagenerstellerQuery13.sql
  FrontEnd/readme.md
Labels: Aprobado por alguno, Sprint 2

#70 Se agregan las pruebas unitarias para BeneficiosQuery
  BackEnd/backend-planilla/PlanillaTest/BeneficioQueryTests/CrearBeneficioTest.cs
  BackEnd/backend-planilla/PlanillaTest/BeneficioQueryTests/GetBeneficiosTest.cs
  BackEnd/backend-planilla/PlanillaTest/BeneficioQueryTests/ModificarBeneficioTest.cs
  BackEnd/backend-planilla/backend-planilla/Application/BeneficiosQuery.cs
Labels: Aprobado por alguno

#71 Actualización tablas planilla
  DB/scripts/VorlagenerstellerQuery13.sql
Labels: Aprobado por alguno, Sprint 2

#73 Query con el trigger
  DB/scripts/VorlagenerstellerQuery14.sql
Labels: Aprobado por alguno, Sprint 2

#74 Unit tests
  BackEnd/backend-planilla/PlanillaTest/EmpleadoQueryTest.cs
  BackEnd/backend-planilla/PlanillaTest/EmpresaQueryTest.cs
  BackEnd/backend-planilla/backend-planilla/Application/EmpleadoQuery.cs
  FrontEnd/frontend-planilla/src/components/dueno/ListaEmpleados.vue
Labels: Aprobado por alguno, Sprint 2

#76 Rachit
  BackEnd/backend-planilla/PlanillaTest/GetDeduccionBeneficiosQueryTests.cs
  BackEnd/backend-planilla/backend-planilla/API/BeneficioEmpleadoController.cs
  BackEnd/backend-planilla/backend-planilla/API/DuenoController.cs
  BackEnd/backend-planilla/backend-planilla/Application/GetDeduccionBeneficiosQuery.cs
  BackEnd/backend-planilla/backend-planilla/Domain/DeduccionBeneficioModel.cs
  BackEnd/backend-planilla/backend-planilla/Infraestructure/EmpleadoRepository.cs
  BackEnd/backend-planilla/backend-planilla/Infraestructure/IEmpleadoRepository.cs
  BackEnd/backend-planilla/backend-planilla/Program.cs
  FrontEnd/frontend-planilla/src/components/dueno/Planilla.vue
Labels: Sprint 2

#77 Unit Tests calculo planilla mensual
  BackEnd/backend-planilla/PlanillaTest/CalculoPlanillaMensualTest.cs
  BackEnd/backend-planilla/backend-planilla/Application/CalcularDeduccionesPlanilla.cs
  BackEnd/backend-planilla/backend-planilla/Domain/DeduccionesPlanillaModel.cs
  DB/scripts/VorlagenerstellerQuery14.sql
Labels: Aprobado por alguno, Sprint 2

#92 Se finaliza cálculo mensual y quincenal con sus pruebas respectivas
  BackEnd/backend-planilla/PlanillaTest/CalculoDeduccionesObligatoriasTest.cs
  BackEnd/backend-planilla/PlanillaTest/CalculoPlanillaMensualTest.cs
  BackEnd/backend-planilla/backend-planilla/API/DeduccionesPlanillaController.cs
  BackEnd/backend-planilla/backend-planilla/Application/CalcularDeduccionesPlanilla.cs
  BackEnd/backend-planilla/backend-planilla/Application/CalculoDeduccionesObligatorias.cs
  BackEnd/backend-planilla/backend-planilla/Application/ICalculoDeduccionesObligatorias.cs
  BackEnd/backend-planilla/backend-planilla/Domain/DeduccionesObligatoriasModel.cs
  BackEnd/backend-planilla/backend-planilla/Domain/DeduccionesPlanillaModel.cs
  BackEnd/backend-planilla/backend-planilla/Program.cs
Labels: Aprobado por alguno, Sprint 3, Inicio Sprint 3

#98 Se añade query17
  DB/scripts/VorlagenerstellerQuery17.sql
Labels: Aprobado por alguno, Sprint 3

#99 Reportes 4 - pago planilla empleador
  BackEnd/backend-planilla/PlanillaTest/ReportesQueryTest.cs
  BackEnd/backend-planilla/backend-planilla/API/ReportesController.cs
  BackEnd/backend-planilla/backend-planilla/Application/IReportesQuery.cs
  BackEnd/backend-planilla/backend-planilla/Application/ReportesQuery.cs
  BackEnd/backend-planilla/backend-planilla/Domain/ReportePagoEmpleadoDTO.cs
  BackEnd/backend-planilla/backend-planilla/Domain/ReportePagoEmpresaDTO.cs
  BackEnd/backend-planilla/backend-planilla/Infraestructure/DuenoHandler.cs
  BackEnd/backend-planilla/backend-planilla/Infraestructure/IReportesRepository.cs
  BackEnd/backend-planilla/backend-planilla/Infraestructure/ReportesRepository.cs
  FrontEnd/frontend-planilla/src/components/RegistrarDueno.vue
  FrontEnd/frontend-planilla/src/components/dueno/ListaBeneficios.vue
  FrontEnd/frontend-planilla/src/components/dueno/ListaEmpleados.vue
  FrontEnd/frontend-planilla/src/components/dueno/ReportePagoEmpresa.vue
  FrontEnd/frontend-planilla/src/components/empleado/RegistrarHoras.vue
  FrontEnd/frontend-planilla/src/components/empleado/ReportePagoPlanilla.vue
  FrontEnd/frontend-planilla/src/components/header/AppHeader.vue
  FrontEnd/frontend-planilla/src/components/modals/ModalAgregarBeneficios.vue
  FrontEnd/frontend-planilla/src/components/modals/ModalEditarEmpleado.vue
  FrontEnd/frontend-planilla/src/components/modals/ModalModificarBeneficio.vue
  FrontEnd/frontend-planilla/src/components/modals/ModalRegistrarEmpresa.vue
  FrontEnd/frontend-planilla/src/main.js
Labels: Sprint 3

#101 Se modifico GetDeducciones para que use Cedula en lugar del token
  BackEnd/backend-planilla/backend-planilla/API/DeduccionesBeneficiosController.cs
  BackEnd/backend-planilla/backend-planilla/API/EmpresaController.cs
  BackEnd/backend-planilla/backend-planilla/Application/GetDeduccionBeneficiosQuery.cs
  BackEnd/backend-planilla/backend-planilla/Application/IGetDeduccionBeneficiosQuery.cs
  BackEnd/backend-planilla/backend-planilla/Infraestructure/EmpleadoRepository.cs
  BackEnd/backend-planilla/backend-planilla/Infraestructure/IEmpleadoRepository.cs
Labels: Aprobado por alguno, Sprint 3

#102 Elige Beneficios
  BackEnd/backend-planilla/PlanillaTest/BeneficioQueryTest.cs
  BackEnd/backend-planilla/PlanillaTest/GetDeduccionBeneficiosQueryTests.cs
  BackEnd/backend-planilla/backend-planilla/API/BeneficioEmpleadoController.cs
  BackEnd/backend-planilla/backend-planilla/Application/BeneficioQuery.cs
  BackEnd/backend-planilla/backend-planilla/Application/BeneficiosQuery.cs
  BackEnd/backend-planilla/backend-planilla/Application/iBeneficioQuery.cs
  BackEnd/backend-planilla/backend-planilla/Infraestructure/BeneficioRepository.cs
  BackEnd/backend-planilla/backend-planilla/Infraestructure/IBeneficioRepository.cs
  DB/scripts/VorlagenerstellerQuery18.sql
  FrontEnd/frontend-planilla/src/App.vue
  FrontEnd/frontend-planilla/src/components/dueno/ListaBeneficios.vue
  FrontEnd/frontend-planilla/src/components/empleado/BeneficiosSeleccionados.vue
Labels: Aprobado por alguno, Sprint 3
